default:
	gcc transformer1.c -o transformer1
	gcc transformer2.c -o transformer2
	gcc transformer3.c -o transformer3
	g++ magic_transformer.cpp -o magic_transformer

clean:
	rm -f transformer1 transformer2 transformer3 magic_transformer